// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRequest) Reset()         { *m = UserRequest{} }
func (m *UserRequest) String() string { return proto.CompactTextString(m) }
func (*UserRequest) ProtoMessage()    {}
func (*UserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *UserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRequest.Unmarshal(m, b)
}
func (m *UserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRequest.Marshal(b, m, deterministic)
}
func (m *UserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRequest.Merge(m, src)
}
func (m *UserRequest) XXX_Size() int {
	return xxx_messageInfo_UserRequest.Size(m)
}
func (m *UserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserRequest proto.InternalMessageInfo

func (m *UserRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UserResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}
func (*UserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *UserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponse.Unmarshal(m, b)
}
func (m *UserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponse.Marshal(b, m, deterministic)
}
func (m *UserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponse.Merge(m, src)
}
func (m *UserResponse) XXX_Size() int {
	return xxx_messageInfo_UserResponse.Size(m)
}
func (m *UserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponse proto.InternalMessageInfo

func (m *UserResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UserPageRequest struct {
	Page                 int32    `protobuf:"varint,1,opt,name=Page,proto3" json:"Page,omitempty"`
	PageNo               int32    `protobuf:"varint,2,opt,name=PageNo,proto3" json:"PageNo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserPageRequest) Reset()         { *m = UserPageRequest{} }
func (m *UserPageRequest) String() string { return proto.CompactTextString(m) }
func (*UserPageRequest) ProtoMessage()    {}
func (*UserPageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *UserPageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserPageRequest.Unmarshal(m, b)
}
func (m *UserPageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserPageRequest.Marshal(b, m, deterministic)
}
func (m *UserPageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserPageRequest.Merge(m, src)
}
func (m *UserPageRequest) XXX_Size() int {
	return xxx_messageInfo_UserPageRequest.Size(m)
}
func (m *UserPageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserPageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserPageRequest proto.InternalMessageInfo

func (m *UserPageRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *UserPageRequest) GetPageNo() int32 {
	if m != nil {
		return m.PageNo
	}
	return 0
}

type UserPageResponse struct {
	Page                 int32    `protobuf:"varint,1,opt,name=Page,proto3" json:"Page,omitempty"`
	PageNo               int32    `protobuf:"varint,2,opt,name=PageNo,proto3" json:"PageNo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserPageResponse) Reset()         { *m = UserPageResponse{} }
func (m *UserPageResponse) String() string { return proto.CompactTextString(m) }
func (*UserPageResponse) ProtoMessage()    {}
func (*UserPageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *UserPageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserPageResponse.Unmarshal(m, b)
}
func (m *UserPageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserPageResponse.Marshal(b, m, deterministic)
}
func (m *UserPageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserPageResponse.Merge(m, src)
}
func (m *UserPageResponse) XXX_Size() int {
	return xxx_messageInfo_UserPageResponse.Size(m)
}
func (m *UserPageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserPageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserPageResponse proto.InternalMessageInfo

func (m *UserPageResponse) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *UserPageResponse) GetPageNo() int32 {
	if m != nil {
		return m.PageNo
	}
	return 0
}

func init() {
	proto.RegisterType((*UserRequest)(nil), "pb.UserRequest")
	proto.RegisterType((*UserResponse)(nil), "pb.UserResponse")
	proto.RegisterType((*UserPageRequest)(nil), "pb.UserPageRequest")
	proto.RegisterType((*UserPageResponse)(nil), "pb.UserPageResponse")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 208 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x90, 0x41, 0x4b, 0x87, 0x40,
	0x14, 0xc4, 0x73, 0x5b, 0x85, 0x5e, 0x91, 0xf2, 0x8a, 0x10, 0x4f, 0xb2, 0x27, 0x21, 0x10, 0xd2,
	0x73, 0xdd, 0x85, 0x90, 0xd8, 0xe8, 0x03, 0x68, 0xbe, 0xc2, 0x43, 0xee, 0xb6, 0xab, 0x7d, 0xfe,
	0x70, 0x55, 0xb4, 0x5b, 0xff, 0xd3, 0xce, 0xcc, 0xf2, 0x63, 0x98, 0x07, 0x30, 0x59, 0x32, 0xb9,
	0x36, 0x6a, 0x54, 0xc8, 0x74, 0x2b, 0x1e, 0xe0, 0xf2, 0xcd, 0x92, 0x91, 0xf4, 0x3d, 0x91, 0x1d,
	0xf1, 0x1a, 0x58, 0xd5, 0xc5, 0x5e, 0xea, 0x65, 0xe7, 0x92, 0x55, 0x1d, 0x22, 0xf0, 0xba, 0xf9,
	0xa2, 0x98, 0xa5, 0x5e, 0x76, 0x21, 0x9d, 0x16, 0x05, 0x5c, 0x2d, 0x88, 0xd5, 0x6a, 0xb0, 0xf4,
	0x2f, 0xe6, 0x11, 0xc2, 0x99, 0x79, 0x69, 0x3e, 0x69, 0xab, 0x42, 0xe0, 0xb3, 0x75, 0xa0, 0x2f,
	0x9d, 0xc6, 0x3b, 0x08, 0xe6, 0xb7, 0x56, 0x0e, 0xf6, 0xe5, 0xea, 0xc4, 0x13, 0x44, 0x3b, 0xbe,
	0xd6, 0x9e, 0xc0, 0x17, 0x6a, 0x59, 0xf9, 0x4a, 0xe6, 0xa7, 0x7f, 0x27, 0xbc, 0x07, 0x5e, 0x0d,
	0x1f, 0x0a, 0xc3, 0x5c, 0xb7, 0xf9, 0x61, 0x7e, 0x12, 0xed, 0xc1, 0xd2, 0x22, 0xce, 0xb0, 0x04,
	0xfe, 0xdc, 0xdb, 0x11, 0x6f, 0xb6, 0xbf, 0xc3, 0x88, 0xe4, 0xf6, 0x6f, 0xb8, 0x41, 0x6d, 0xe0,
	0x2e, 0x5c, 0xfe, 0x06, 0x00, 0x00, 0xff, 0xff, 0x88, 0x7b, 0xfc, 0xbb, 0x6f, 0x01, 0x00, 0x00,
}
